version: v2beta1
name: vcluster

# Variables used
vars:
  # Make sure vcluster is the default namespace
  DEVSPACE_FLAGS: "-n vcluster"
  SYNCER_IMAGE: ghcr.io/loft-sh/loft-enterprise/dev-vcluster

# Images DevSpace will build for vcluster
images:
  vcluster:
    dockerfile: ./Dockerfile
    image: ${SYNCER_IMAGE}
    rebuildStrategy: ignoreContextChanges
    target: builder
    buildKit: {}

# Deployment used for vcluster
deployments:
  vcluster-k0s:
    helm:
      releaseName: vcluster
      chart:
        name: ./charts/k0s
      values:
        service:
          type: NodePort
        serviceCIDR: $([ $1 == "dev" ] && vcluster get service-cidr || echo "null")
        tolerations:
          - operator: "Exists"
        serviceAccount:
          create: false
          name: default
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        syncer:
          image: ${SYNCER_IMAGE}

  vcluster-k8s:
    helm:
      releaseName: vcluster
      chart:
        name: ./charts/k8s
      values:
        job:
          enabled: false
        service:
          type: NodePort
        serviceCIDR: $([ $1 == "dev" ] && vcluster get service-cidr || echo "null")
        tolerations:
          - operator: "Exists"
        serviceAccount:
          create: false
          name: default
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        syncer:
          image: ${SYNCER_IMAGE}

  vcluster-k3s:
    helm:
      releaseName: vcluster
      chart:
        name: ./charts/k3s
      values:
        service:
          type: NodePort
        serviceCIDR: $([ $1 == "dev" ] && vcluster get service-cidr || echo "null")
        tolerations:
          - operator: "Exists"
        serviceAccount:
          create: false
          name: default
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        syncer:
          image: ${SYNCER_IMAGE}

# Dev Configuration for vcluster
dev:
  vcluster:
    imageSelector: ${SYNCER_IMAGE}
    container: syncer
    workingDir: /vcluster-dev
    terminal:
      command: "./devspace_start.sh"
    ports:
    - port: 2346:2345
    sync:
    - excludePaths:
        - '**'
        - '!/pkg'
        - 'cmd/vclusterctl/cmd/charts'
        - '!/cmd'
        - '!/vendor'
        - '!/hack'
        - '!/go.mod'
        - '!/go.sum'
        - '!/devspace_start.sh'
        - '!/manifests'

profiles:
  - name: dev-hostpath-mapper
    patches:
      - op: remove
        path: dev.vcluster.imageSelector
      - op: remove
        path: dev.vcluster.container
      - op: add
        path: dev.vcluster.labelSelector
        value:
          component: hostpath-mapper
    merge:
      deployments:
        vcluster-k3s:
          helm:
            values:
              hostpathMapper:
                image: ${SYNCER_IMAGE}
                enabled: true
                dev: true
              syncer:
                livenessProbe:
                  enabled: false
                readinessProbe:
                  enabled: false
                extraArgs:
                  - start
                  - --tls-san=vcluster

# Pipelines used for vcluster
pipelines:
  dev:
    flags:
      - name: distro
        description: "Virtual cluster distribution to use"
        default: "k3s"
        type: string
    run: |-
      # Deploy the vcluster
      run_pipelines deploy --set-flag distro=$(get_flag distro)
      
      # Start dev mode
      start_dev --all

  deploy:
    flags:
      - name: distro
        description: "Virtual cluster distribution to use"
        default: "k3s"
        type: string
    run: |-
      # Make sure pull secrets are there
      ensure_pull_secrets --all
      
      # Build the vcluster image
      build_images --all
      
      # Deploy the vcluster
      if is_equal $(get_flag distro) k8s; then
        kubectl apply -f ./hack/vcluster-certs.yaml -n ${DEVSPACE_NAMESPACE}
        create_deployments vcluster-k8s  
      elif is_equal $(get_flag distro) k0s; then
        create_deployments vcluster-k0s
      else
        create_deployments vcluster-k3s
      fi

  purge:
    run: |-
      # Purge the vcluster
      run_default_pipeline purge
      
      # Make sure the pvcs are deleted as well
      kubectl delete pvc --all -n ${DEVSPACE_NAMESPACE}
