{{- if .Values.logmapper.enabled }}
apiVersion: apps/v1
{{- if not .Values.logmapper.dev }}
kind: DaemonSet
{{- else  }}
kind: Deployment
{{- end }}
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster-logmapper
    component: logmapper
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  {{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.logmapper.dev }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: vcluster-logmapper
      release: {{ .Release.Name }}
      component: logmapper
  template:
    metadata:
      labels:
        app: vcluster-logmapper
        release: {{ .Release.Name }}
        component: logmapper
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- else }}
      serviceAccountName: vc-{{ .Release.Name }}
      {{- end }}
      containers:
      - name: logmapper
        {{- if .Values.logmapper.image }}
        image: "{{ .Values.defaultImageRegistry }}{{ .Values.logmapper.image }}"
        {{- else }}
        image: "{{ .Values.defaultImageRegistry }}loftsh/vcluster:{{ .Chart.Version }}"
        {{- end }}
        {{- if .Values.syncer.workingDir }}
        workingDir: {{ .Values.syncer.workingDir }}
        {{- end }}
        command:
          - /vcluster
        args:
          - maplogs
          - --name={{ .Release.Name }}
          - --target-namespace={{ .Release.Namespace }}
        volumeMounts:
          - name: logs
            mountPath: /var/log
          - name: virtual-logs
            mountPath: /tmp/vcluster/{{ .Release.Namespace }}/{{ .Release.Name }}/log
          - name: pod-logs
            mountPath: /var/log/pods
          - name: virtual-pod-logs
            mountPath: /tmp/vcluster/{{ .Release.Namespace }}/{{ .Release.Name }}/log/pods
          - name: kubeconfig
            mountPath: /data/server/tls
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        - name: virtual-logs
          hostPath:
            path: /tmp/vcluster/{{ .Release.Namespace }}/{{ .Release.Name }}/log
        - name: pod-logs
          hostPath:
            path: /var/log/pods
        - name: virtual-pod-logs
          hostPath:
            path: /tmp/vcluster/{{ .Release.Namespace }}/{{ .Release.Name }}/log/pods
        - name: kubeconfig
          secret:
            secretName: vc-{{ .Release.Name }}
{{ end }}

