{{- if and .Values.isolation.enabled .Values.isolation.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-limit-range
spec:
  limits:
  - default:
      {{- range $key, $val := .Values.isolation.limitRange.default }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    defaultRequest:
      {{- range $key, $val := .Values.isolation.limitRange.defaultRequest }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    type: Container
{{- end }}
